version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass@2024
      MYSQL_DATABASE: MembersDB
      MYSQL_USER: mysql
      MYSQL_PASSWORD: pass@2024
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
